### PR TITLE
CC7: Readme, removing eth0 config, removing dns config, installing py3

### PR DESCRIPTION
**Pull request by mkowalski**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5)

### CODE REVIEW

**Review by kormat — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5)* status: all files reviewed, 1 unresolved discussion (waiting on @mkowalski)

___
*[README.anapaya.md, line 8 at r1](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5#-M1_0wCK3j47FzdeTz5a:-M1_0wCL9HSPATlrDAcy:b-pbu3rx) ([raw file](https://github.com/anapaya/vagrant-lxc-base-boxes/blob/6c2f6c8c3d499d38b1160f08f1779302a3968e59/README.anapaya.md#L8)):*
> ```Markdown
> - `cd vagrant-lxc-base-boxes`
> - `make xenial` for building Ubuntu 16.04
> - `EPEL=1 make 7` for building CentOS 7 with EPEL repositories
> ```

Drop `EPEL=1`, as discussed.

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kormat)

___
*[README.anapaya.md, line 8 at r1](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5#-M1_0wCK3j47FzdeTz5a:-M1_3TMU44qjc-u3CiO_:b-896fix) ([raw file](https://github.com/anapaya/vagrant-lxc-base-boxes/blob/6c2f6c8c3d499d38b1160f08f1779302a3968e59/README.anapaya.md#L8)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Drop `EPEL=1`, as discussed.
</blockquote></details>

Done.

**Review by kormat — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5)* status: all files reviewed, 1 unresolved discussion (waiting on @mkowalski)

___
*[centos/clean.sh, line 22 at r2](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5#-M1_3fsHAkUjDey_P07I:-M1_3fsHAkUjDey_P07J:bousbr2) ([raw file](https://github.com/anapaya/vagrant-lxc-base-boxes/blob/ef997bd4ef4afe689831394c0bee568c7e1b3adf/centos/clean.sh#L22)):*
> ```Shell
> 
> log 'Remove stale dns configuration'
> rm -f ${ROOTFS}/etc/resolv.conf
> ```

It might be better to have this be empty, rather than missing.

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kormat)

___
*[centos/clean.sh, line 22 at r2](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5#-M1_3fsHAkUjDey_P07I:-M1_4TSa05u9RfzxdkO-:b-896fix) ([raw file](https://github.com/anapaya/vagrant-lxc-base-boxes/blob/ef997bd4ef4afe689831394c0bee568c7e1b3adf/centos/clean.sh#L22)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It might be better to have this be empty, rather than missing.
</blockquote></details>

Done.

**Review by kormat — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/5#-:-M1_GwPo2WQLvKVHdjnD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
