### PR TITLE
Upgrade LXC base box

### PR DESCRIPTION
**Pull request by mkowalski**
* remove custom PPA for Wireguard
* install Wireguard from cloudsmith
* install base tools from Ansible

This change is [Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/7)

### CODE REVIEW

**Review by worxli — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkowalski)

**Review by mkowalski — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lskillen** [comment]
@mkowalski Hey Mateusz. Lee from @cloudsmith-io here. Did you mean to expose your internal entitlement token here:
https://github.com/Anapaya/vagrant-lxc-base-boxes/pull/7/files#diff-fbe0bf40571095a94e3172f4844fa8b7R50

We'd recommend setting secrets, such as entitlement tokens, in your environment; then interpolating them. :-)

Ignore me if not an issue!

**Comment by mkowalski** [comment]
For the future us: https://cloudsmith.io/~anapaya/repos/internal/entitlements/?show_disabled=true - the token is disabled now and should be enabled by whoever is going to build a new image

**Pull request merged**
