### PR TITLE
Update Readme.md: Create and upload anapaya lxc xenial box

### PR DESCRIPTION
**Pull request by Hermain**
TODO: Reference this Readme from the Ansible repo once its accepted and merged

---
This change is [Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3)

### CODE REVIEW

**Review by kormat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Hermain)

*[a discussion](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3#-LhGYsjoAa7EbXK1-URY:-LhGYsjoAa7EbXK1-URZ:bsstaa5) (no related file):*
Ah, no. Please don't edit upstream's `README.md`. That's why i suggested
> - add a README.anapaya.md (or similar) to the vagrant lxc box git repo

---

**Review by Hermain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kormat)

*[a discussion](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3#-LhGYsjoAa7EbXK1-URY:-LhK_Nto4rHJUviRpyJJ:bb6un1j) (no related file):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Ah, no. Please don't edit upstream's `README.md`. That's why i suggested
> - add a README.anapaya.md (or similar) to the vagrant lxc box git repo
</blockquote></details>

Done

---

**Review by kormat — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3)* status: all files reviewed, 2 unresolved discussions (waiting on @Hermain and @kormat)

___
*[README.anapaya.md, line 12 at r2](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3#-LhKa6xr54uwSxOQC2vN:-LhKa6xsADtV8SAIasPL:b-qjdw35) ([raw file](https://github.com/anapaya/vagrant-lxc-base-boxes/blob/adfc5a8b4d0e3da1c10d1edc33c61da47308f224/README.anapaya.md#L12)):*
> ```Markdown
> - Get permissions for our Vagrant cloud
> - Select anapaya/lxc-xenial-amd64
> - Create a New Version - Version: <DATE>
> ```

One thing - the version is actually the date with 2 extra digits, so that we can do multiple releases in a day if needed.

**Review by Hermain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kormat)

___
*[README.anapaya.md, line 12 at r2](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3#-LhKa6xr54uwSxOQC2vN:-LhKculs7uoDYJJWfRdW:b-896fix) ([raw file](https://github.com/anapaya/vagrant-lxc-base-boxes/blob/adfc5a8b4d0e3da1c10d1edc33c61da47308f224/README.anapaya.md#L12)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

One thing - the version is actually the date with 2 extra digits, so that we can do multiple releases in a day if needed.
</blockquote></details>

Done.

**Review by kormat — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vagrant-lxc-base-boxes/3#-:-LheCYlvBl7fcN6PUp8a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
